//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuPhiQuyenGop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanBoQuanLy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CanBoQuanLy()
        {
            this.HoGiaDinhQuyenGops = new HashSet<HoGiaDinhQuyenGop>();
            this.ThuPhis = new HashSet<ThuPhi>();
        }
    
        public int CanBoQuanLyID { get; set; }
        public string TenCanBo { get; set; }
        public string ChucVu { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoGiaDinhQuyenGop> HoGiaDinhQuyenGops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThuPhi> ThuPhis { get; set; }
    }
}
