//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuPhiQuyenGop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoGiaDinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoGiaDinh()
        {
            this.HoGiaDinhQuyenGops = new HashSet<HoGiaDinhQuyenGop>();
        }
    
        public int HoGiaDinhID { get; set; }
        public string TenChuHo { get; set; }
        public Nullable<int> SoNhanKhau { get; set; }
        public string DiaChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoGiaDinhQuyenGop> HoGiaDinhQuyenGops { get; set; }
    }
}
