//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuPhiQuyenGop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoGiaDinhQuyenGop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoGiaDinhQuyenGop()
        {
            this.ChiTietQuyenGops = new HashSet<ChiTietQuyenGop>();
            this.ThongKeQuyenGops = new HashSet<ThongKeQuyenGop>();
        }
    
        public int HoGiaDinhQuyenGop1 { get; set; }
        public Nullable<int> QuyenGopID { get; set; }
        public Nullable<int> HoGiaDinhID { get; set; }
        public Nullable<int> CanBoQuanLyID { get; set; }
        public Nullable<decimal> SoTienDongGop { get; set; }
    
        public virtual CanBoQuanLy CanBoQuanLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietQuyenGop> ChiTietQuyenGops { get; set; }
        public virtual HoGiaDinh HoGiaDinh { get; set; }
        public virtual QuyenGop QuyenGop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongKeQuyenGop> ThongKeQuyenGops { get; set; }
    }
}
