//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuPhiQuyenGop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLThuPhiQuyenGopEntities : DbContext
    {
        public QLThuPhiQuyenGopEntities()
            : base("name=QLThuPhiQuyenGopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CanBoQuanLy> CanBoQuanLies { get; set; }
        public virtual DbSet<ChiTietQuyenGop> ChiTietQuyenGops { get; set; }
        public virtual DbSet<HoGiaDinh> HoGiaDinhs { get; set; }
        public virtual DbSet<HoGiaDinhQuyenGop> HoGiaDinhQuyenGops { get; set; }
        public virtual DbSet<QuyenGop> QuyenGops { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThongKeQuyenGop> ThongKeQuyenGops { get; set; }
        public virtual DbSet<ThongKeThuPhiHangThang> ThongKeThuPhiHangThangs { get; set; }
        public virtual DbSet<ThuPhi> ThuPhis { get; set; }
    }
}
