//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuPhiQuyenGop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyenGop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuyenGop()
        {
            this.HoGiaDinhQuyenGops = new HashSet<HoGiaDinhQuyenGop>();
        }
    
        public int QuyenGopID { get; set; }
        public Nullable<int> TenVanDong { get; set; }
        public Nullable<System.DateTime> NgayVanDong { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string NoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoGiaDinhQuyenGop> HoGiaDinhQuyenGops { get; set; }
    }
}
