//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuPhiQuyenGop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuPhi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThuPhi()
        {
            this.ThongKeThuPhiHangThangs = new HashSet<ThongKeThuPhiHangThang>();
        }
    
        public int ThuPhiID { get; set; }
        public Nullable<int> HoGiaDinhID { get; set; }
        public Nullable<int> CanBoQuanLyID { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
        public Nullable<decimal> SoTienThuPhi { get; set; }
    
        public virtual CanBoQuanLy CanBoQuanLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongKeThuPhiHangThang> ThongKeThuPhiHangThangs { get; set; }
    }
}
